blog/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.BlogPaginatorView.as_view(), name='index'),
    url(r'^page/(?P<page>[0-9]+)$', views.BlogPaginatorView.as_view(), name='paginator'),
    url(r'^tags/(?P<tag_id>[0-9]+)/page/(?P<page>[0-9]+)$', views.BlogPaginatorView.as_view(), name='tags'),
    url(r'^(?P<pk>[0-9]+)$', views.BlogDetailView.as_view(), name='detail'),
    url(r'^comment/(?P<pk>[0-9]+)/$', views.BlogCommentRedirectView.as_view(), name='blog_redirect'),
    url(r'^search/$', views.BlogSearchView.as_view(), name='blog_search')
]

jaydenfoo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from blog import views as blog_views
from .views import RegisterView


urlpatterns = [
    url(r'^$', blog_views.BlogPaginatorView.as_view()),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tools/', include('tools.urls', namespace='tools')),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
    url(r'^album/', include('album.urls', namespace='album')),
    url(r'^register/$', RegisterView, name='register'),
    url(r'^wechat/', include('wechat.urls', namespace='wechat')),
    url(r'^markdownx/', include('markdownx.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tools/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.tools_index_view, name='index'),
    url(r'^tempo$', views.tools_tempo_view, name='tempo'),
    url(r'^weather$', views.tools_weather_view, name='weather'),
    url(r'^weather-statistics$', views.tools_weather_statistics, name='weather_statistics'),
    url(r'^schedule$', views.schedule_view, name='schedule'),
]

tools/models.py
# -*- coding: utf-8 -*-
from django.db import models


class WeatherNow(models.Model):
    # basic
    city = models.CharField(max_length=20)
    city_id = models.CharField('city id', max_length=20)
    update_loc = models.CharField('update time(local) from weather api', max_length=20)
    update_utc = models.CharField('update time(utc) from weather api', max_length=20)
    # now
    # 天气情况代码说明 https://www.heweather.com/documents/condition
    cond_code = models.CharField('weather condition code', max_length=20)
    cond_txt = models.CharField('weather condition text', max_length=20)
    fl = models.CharField('sendible temperature', max_length=20)
    hum = models.CharField('relative humidity', max_length=20)
    pcpn = models.CharField('precipitation', max_length=20)
    pres = models.CharField('pressure', max_length=20)
    tmp = models.CharField('temperature', max_length=20)
    vis = models.CharField('visibility', max_length=20)
    wind_deg = models.CharField('wind degree', max_length=20)
    wind_dir = models.CharField('wind direction', max_length=20)
    wind_sc = models.CharField('wind scale', max_length=20)
    wind_spd = models.CharField('wind speed', max_length=20)
    # aqi
    aqi_index = models.CharField(max_length=20)
    aqi_qlty = models.CharField(max_length=20)

    def __str__(self):
        return self.city+'  '+self.update_utc

class WeatherForecast(models.Model):
    fc_city = models.CharField('city name', max_length=20)
    fc_index = models.IntegerField()
    # 天文指数
    fc_mr = models.CharField('moon rise time', max_length=20)
    fc_ms = models.CharField('moon set time', max_length=20)
    fc_sr = models.CharField('sun rise time', max_length=20)
    fc_ss = models.CharField('sun set time', max_length=20)
    # condition
    fc_txt_d = models.CharField('day condition', max_length=20)
    fc_txt_n = models.CharField('night condition', max_length=20)
    # general
    fc_date = models.CharField(max_length=20)
    fc_hum = models.CharField('humidity', max_length=20)
    fc_pcpn = models.CharField('precipitation', max_length=20)
    fc_pop = models.CharField('precipitation optitunity', max_length=20)
    fc_pres = models.CharField('pressure', max_length=20)
    fc_uv = models.CharField('uv', max_length=20)
    fc_vis = models.CharField('visibility', max_length=20)
    # temperature
    fc_tmp_max = models.CharField('maximum temperature', max_length=20)
    fc_tmp_min = models.CharField('minimum temperature', max_length=20)
    # wind
    fc_wind_deg = models.CharField('wind degree', max_length=20)
    fc_wind_dir = models.CharField('wind direction', max_length=20)
    fc_wind_sc = models.CharField('wind scale', max_length=20)
    fc_wind_spd = models.CharField('wind speed', max_length=20)
    # forecast foreignkey
    weathernow = models.ForeignKey('WeatherNow', on_delete=models.CASCADE, )

    def __str__(self):
        return self.fc_date


class Weather(models.Model):
    city = models.CharField(max_length=20, editable=False)
    city_id = models.CharField(max_length=20, editable=False)
    updata_time = models.DateTimeField(auto_now=True, editable=False)
    aqi = models.IntegerField(verbose_name='空气质量指数', editable=False)
    pm25 = models.IntegerField(editable=False)
    tmp = models.IntegerField(verbose_name='温度', editable=False)
    condition = models.IntegerField(verbose_name='天气情况', editable=False)
    pcpn = models.IntegerField(verbose_name='降雨量mm')
    vis = models.IntegerField(verbose_name='能见度km')
    wind_direction = models.IntegerField(verbose_name='风向', editable=False)
    wind_speed = models.IntegerField(verbose_name='风速', editable=False)
    humidity = models.IntegerField(verbose_name='湿度', editable=False)

    def __str__(self):
        return self.city + '  ' + self.updata_time.strftime('%Y-%m-%d-%H-%M') + '   id=' + str(self.id)

class ScheduleItem(models.Model):
    content = models.TextField(max_length=500, verbose_name='计划内容')
    deadline = models.DateTimeField(verbose_name='截止时间')
    pub_date = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    finish = models.BooleanField(default=False)
    user = models.CharField(max_length=20)

    def __unicode__(self):
        return self.user

tools/forms.py
#!/usr/bin/env python
# encoding: utf-8
from django import forms

from .models import ScheduleItem


class ScheduleItemForm(forms.ModelForm):
    class Meta:
        model = ScheduleItem
        fields = ['content', 'deadline', 'user', 'finish']

tools/views.py
import collections
from datetime import datetime, timedelta, time

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.db.models import Max, Min

from .models import Weather, WeatherNow, ScheduleItem
from .forms import ScheduleItemForm


def tools_index_view(request):
    return render(request, 'tools/tools_index.html')


def tools_tempo_view(request):
    return render(request, 'tools/tools_tempo.html')


def tools_weather_view(request):
    weather_now = WeatherNow.objects.all()
    return render(request, 'tools/tools_weather.html', {'weather_now': weather_now})


def tools_weather_statistics(request):
    weather_data = collections.OrderedDict()
    weather_data['上海'] = Weather.objects.filter(city='上海').order_by('-updata_time')
    weather_data['北京'] = Weather.objects.filter(city='北京').order_by('-updata_time')
    weather_data['厦门'] = Weather.objects.filter(city='厦门').order_by('-updata_time')
    weather_data['拉萨'] = Weather.objects.filter(city='拉萨').order_by('-updata_time')

    data = collections.OrderedDict()
    for city in weather_data:
        # 0-50优，51-100良,101-150轻度污染,151-200中度污染,201-300重度污染,300-500严重污染,>500爆表
        aqi_counter = collections.OrderedDict({'优':0, '良':0, '轻度污染':0, '中度污染':0, '重度污染':0, '严重污染':0, '爆表':0})
        # 最新的日期
        latest_date = weather_data[city].first().updata_time.date()
        # 最早的日期
        oldest_date = weather_data[city].last().updata_time.date()

        single_day_info = {}
        single_day_tmp_max = collections.OrderedDict()
        single_day_tmp_min= collections.OrderedDict()
        single_day_aqi_max= collections.OrderedDict()
        data_temp = collections.OrderedDict()

        date_loop = oldest_date
        while date_loop <= latest_date:
            date_loop_start = datetime.combine(date_loop, time.min)
            date_loop_end = datetime.combine(date_loop, time.max)
            single_day_info_temp = weather_data[city].filter(updata_time__gte=date_loop_start, updata_time__lte=date_loop_end)
            if single_day_info_temp:
                #单日气候信息
                single_day_info[date_loop.strftime('%Y-%m-%d')] = single_day_info_temp
                #每日最低最高温度
                single_day_tmp_max[date_loop.strftime('%Y-%m-%d')] = single_day_info_temp.aggregate(Max('tmp'))
                single_day_tmp_min[date_loop.strftime('%Y-%m-%d')] = single_day_info_temp.aggregate(Min('tmp'))
                #每日最高空气质量指数
                single_day_aqi_max[date_loop.strftime('%Y-%m-%d')] = single_day_info_temp.aggregate(Max('aqi'))
            date_loop += timedelta(1)
        #计算每类空气指标的天数
        for key, value in single_day_aqi_max.iteritems():
            aqi_num = int(value['aqi__max'])
            if aqi_num <= 50:
                aqi_counter['优'] += 1
            elif aqi_num > 50 and aqi_num <= 100:
                aqi_counter['良'] += 1
            elif aqi_num > 100 and aqi_num <= 150:
                aqi_counter['轻度污染'] += 1
            elif aqi_num > 150 and aqi_num <=200:
                aqi_counter['中度污染'] += 1
            elif aqi_num > 200 and aqi_num <= 300:
                aqi_counter['重度污染'] += 1
            elif aqi_num > 300 and aqi_num <= 500:
                aqi_counter['严重污染'] +=1
            elif aqi_num > 500:
                aqi_counter['爆表'] += 1

        # 传递到模板的数据
        data_temp['tmp_max'] = single_day_tmp_max
        data_temp['tmp_min'] = single_day_tmp_min
        data_temp['aqi_counter'] = aqi_counter
        data[city] = data_temp

    return render(request, 'tools/tools_weather_statistics.html', {'data':data})


@login_required
def schedule_view(request):
    if request.method == 'POST':
        form = ScheduleItemForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('schedule')
    if request.method == 'GET':
        # 删除条目
        if request.GET.get('action', None) == 'delete':
            item_id = request.GET.get('item_id', None)
            if item_id:
                item_need_delete = ScheduleItem.objects.get(id=item_id)
                # 从数据库中删除
                item_need_delete.delete()
                return HttpResponseRedirect('schedule')
        # 目标达成
        if request.GET.get('action', None) == 'finishCheck':
            item_id = request.GET.get('item_id', None)
            if item_id:
                item_finish = ScheduleItem.objects.get(id=item_id)
                # 从数据库中删除
                item_finish.finish = True
                item_finish.save(update_fields=['finish'])
                return HttpResponseRedirect('schedule')
    items = ScheduleItem.objects.filter(user=request.user.username)
    ItemAddForm = ScheduleItemForm()
    return render(request, 'tools/tools_schedule.html', {'items': items, 'ItemAddForm': ItemAddForm})

tools/templates/tools/tools_index.html
{% extends "base.html" %}

{% block title %} 工具 {% endblock %}


{% block content %}
<div class="container">
	<div class="row">
        <div class="col-md-6 col-sm-6">
            <div class="jumbotron">
                <h1 class="text-center">节拍器</h1>
                <p class="text-center">简单的节拍器，学习乐器时使用</p>
                <p class="text-center"><a href="{% url 'tools:tempo' %}"class="btn btn-success btn-lg">进入</a></p>
            </div>
        </div>
        <div class='col-md-6 col-sm-6'>
            <div class="jumbotron">
                <h1 class="text-center">计划表</h1>
                <p class="text-center">简单的个人计划时间表，需要登录使用</p>
                <p class="text-center"><a href="{% url 'tools:schedule' %}"class="btn btn-success btn-lg">进入</a></p>
            </div>
        </div>
        <div class='col-md-6 col-sm-6'>
            <div class="jumbotron">
                <h1 class="text-center">天气情况</h1>
                <p class="text-center">五城天气预报,实时更新</p>
                <p class="text-center"><a href="{% url 'tools:weather' %}"class="btn btn-success btn-lg">进入</a></p>
            </div>
        </div>
        <div class='col-md-6 col-sm-6'>
            <div class="jumbotron">
                <h1 class="text-center">天气信息统计</h1>
                <p class="text-center">图表展示历史天气统计结果，包括气温走势和空气质量分布</p>
                <p class="text-center"><a href="{% url 'tools:weather_statistics' %}"class="btn btn-success btn-lg">进入</a></p>
            </div>
        </div>
	</div>
</div>
<script type="text/javascript">
//最笨的方法控制导航栏
  $(function () {
    $('#nav_blog').parent().removeClass('active')
    $('#nav_zheteng').parent().addClass('active')
  })
</script>
{% endblock %}}

tools/templates/tools/tools_schedule.html
{% extends 'base.html' %}

{% block title %}Schedule{% endblock %}

{% block content %}
<div class='container'>
{% if user.is_authenticated %}
    <button type='button' class='btn btn-info' data-toggle='modal', data-target='#itemAddModal'>
        新增条目
    </button>
    <hr>
    <!-- 达成的目标 -->
    {% for item in items %}
        {% if item.finish %}
            <div class='alert alert-warning schedule-item', role='alert' data-finish-state='{{item.finish}}'>
                <div class='pull-left'>
                    <span class='label label-default'>创建日期：{{ item.pub_date }}</span>
                    <span class='label label-default'>截止日期：{{ item.deadline }}</span>
                </div>
                <br><br>
                {{ item.content|linebreaks }}
            </div>
        {% endif %}
    {% empty %}
        <p>还没有日程！</p>
    {% endfor %}
    <!-- 未达成目标 -->
    {% for item in items %}
        {% if not item.finish %}
            <div class='alert alert-success schedule-item', role='alert' data-finish-state='{{item.finish}}'>
                <div class='pull-left'>
                    <span class='label label-default'>创建日期：{{ item.pub_date }}</span>
                    <span class='label label-default'>截止日期：{{ item.deadline }}</span>
                </div>
                <br><br>
                {{ item.content|linebreaks }}
                {% if not item.finish %}
                <div class='row'>
                    <hr>
                    <div class='pull-right'>
                        <label class='btn btn-info btn-xs'>
                            <input type='checkbox' class='finishCheck' style='display:none' data-item={{item.id}} />
                            <span class="glyphicon glyphicon-ok"> 完成?</span>
                        </label>
                        &nbsp&nbsp&nbsp
                        <a href="{% url 'tools:schedule' %}?action=delete&item_id={{item.id}}">删除</a>
                        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                    </div>
                </div>
                {% endif %}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

    <!-- Model -->
    <!-- itemAddModal -->
    <div class="modal fade" id="itemAddModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新增计划</h4>
                </div>
                <div class="modal-body">
                    {{ ItemAddForm.non_field_errors }}
                    <form action='{% url 'tools:schedule' %}' method='post'>
                        {% csrf_token %}
                        {{ ItemAddForm.content.errors }}
                        <div class='form-group textarea-align'>
                            {{ ItemAddForm.content.label_tag }}
                            {{ ItemAddForm.content }}
                        </div>
                        {{ ItemAddForm.deadline.errors }}
                        <div class='form-group'>
                            {{ ItemAddForm.deadline.label_tag }}
                            <input type='text' value='' readonly class='form_datetime' name='{{ ItemAddForm.deadline.html_name }}' id='{{ ItemAddForm.deadline.id_for_label }}'>
                        </div>
                        <input type='hidden' name='user' value='{{ request.user.username }}'/>
                        <input type='hidden' name='finish' value=false />
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                            <button type="submit" class="btn btn-primary">保存</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% load static %}
<link rel='stylesheet', href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">
<script src="{% static 'bootstrap/js/bootstrap-datetimepicker.min.js' %}"></script>

<script type='text/javascript'>
    //日期选择插件
    $('.form_datetime').datetimepicker({
            format: 'yyyy-mm-dd hh:ii'
            });
    //点击目标达成按钮后重刷新页面
    $('.finishCheck').change(function() {
            window.location="{{ request.path }}?action=finishCheck&item_id=" + $(this).data('item')
            });

</script>

<style>
    .textarea-align * {
        vertical-align: middle
    }
</style>
{% endblock %}

tools/templates/tools/tools_tempo.html
{% extends "base.html" %}
{% block title %}节拍器{% endblock %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class=" panel panel-info">
          <div class="panel-heading">
            <h3>Simple Tempo</h3>
          </div>
          <div class="panel-body">
            <div class="btn-group" id="checkbox-group" data-toggle="buttons">
	           <label class="btn btn-default active btn-xs">
	             <input type="checkbox" id="checkbox1" autocomplete="off" value="0" aria-label="..." checked>
	             <span class="glyphicon glyphicon-heart"></span>
	           </label>
	           <label class="btn btn-default btn-xs">
	             <input type="checkbox" id="checkbox2" value="1" aria-label="...">
	             <span class="glyphicon glyphicon-heart"></span>
	           </label>
	           <label class="btn btn-default btn-xs">
	             <input type="checkbox" id="checkbox3" value="2" aria-label="...">
	             <span class="glyphicon glyphicon-heart"></span>
	           </label>
	           <label class="btn btn-default btn-xs">
	             <input type="checkbox" id="checkbox4" value="3" aria-label="...">
	             <span class="glyphicon glyphicon-heart"></span>
	           </label>
	          </div>
	          <form class="form-horizontal">
	           <div class="form-group">
	             <label class="col-sm-2 control-label">BMP: </label>
	             <div class="col-sm-10">
	               <input type="text" class="form-control" id="bmp" value="60">
	             </div>
	           </div>
	           <div class="form-group">
	             <label class="col-sm-2 control-label">Beats: </label>
	             <div class="col-sm-10">
	               <input type="text" class="form-control" id="beats" value="4">
	             </div>
	           </div>
	           <div class="form-group">
	             <div class="col-sm-offset-4 col-sm-8">
	               <button type="button" class="btn btn-success" id="play-btn">Play</button>
	             </div>
	           </div>
	          </form>
         </div>
       </div>
     </div>
   </div>
  </div>




  <script>
  //最笨的方法控制导航栏
    $(function () {
      $('#nav_blog').parent().removeClass('active')
      $('#nav_album').parent().removeClass('active')
      $('#nav_zheteng').parent().addClass('active')
    })

    // 简易节拍器，可以设置拍频和拍数和重拍点
    // 参考http://cool.techbrood.com/fiddle/727

    window.AudioContext = window.AudioContext || window.webkitAudioContext;
    var context = new AudioContext();
    var Gain = context.createGain();
    Gain.gain.value = 1000;
    var timer, curTime, beatsPos = 0;
    var boxSelected = [1,0,0,0];

    // 记录被选中的拍子
    function boxCheck() {
    	if(this.checked){
        boxSelected[this.value] = 1;
    	}
    	else {
        boxSelected[this.value] = 0;
    	}
    };

    // 将checkbox的点击事件绑定到函数boxCheck
    $('input:checkbox').change(boxCheck);

    // 点击play按钮，节拍器开始打拍
    $('#play-btn').click(function () {
      curTime = context.currentTime;
      schedule();
    });

    // 拍数输入框事件，改变拍数后重新调整页面上的拍点框
    $('#beats').change(function () {
      var reg = /^[2-9]{1}$/;
      if (reg.test(this.value)) {
        var i, temp, group = $('#checkbox-group');
        group.html("");
        for (i=0; i<this.value; i++) {

          temp = "<label class='btn btn-default btn-xs'><input type='checkbox' id='checkbox"+i+"' value='"+i+"' aria-label='...'><span class='glyphicon glyphicon-heart'></span></label>"
          group.append(temp);
        }
        $('#checkbox0').prop({'checked': true});
        $('#checkbox-group label:first-child').addClass('active');
        $('input:checkbox').change(boxCheck);
        $('input:checkbox').trigger('change');
      }
      });

    // 网页发声函数
    function playSound(t) {
      var note = context.createOscillator();
      // 根据不同的重拍点设置不同的频率
      if (boxSelected[beatsPos]) {
        note.frequency.value = 380;
      }
      else {
        note.frequency.value = 700;
      }
      note.connect(Gain);
      Gain.connect(context.destination);
      // 网页讲在t时间发声
      // 发声0.05秒
      note.start(t);
      note.stop(t + 0.05);
      // 暂时未用到，用来控制拍点框随着拍数有视觉上的跳动
      beatsPos += 1;
      beatsPos = beatsPos%(boxSelected.length);
    }

    // 当实际时间到达应该发声时间的前0.1秒，调用playSound，并重新计算下次发声时间
    function schedule() {
      while (curTime < context.currentTime + 0.1) {
          playSound(curTime);
          updateTime();
      }
      timer = window.setTimeout(schedule, 0.1);
    }

    // 根据拍频计算下次发声的时间，使网页在curTime时间节点发声
    function updateTime() {
      curTime += 60.0 / parseInt($('#bmp').val(), 10);
    }
  </script>
  <style type="text/css">
    .btn span.glyphicon {
	   opacity: 0;
    }
    .btn.active span.glyphicon {
	   opacity: 1;
    }

    label.btn {
      margin-bottom: 20px;
      margin-right: 8px;
    }
  </style>
{% endblock %}

tools/templates/tools/tools_weather.html
{% extends 'base.html' %}

{% block title %}天气情况{% endblock %}

{% block content %}
{% load static %}
<br><br><br><br><br><br><br><br>
<div class='site-content'>
{% for iweather in weather_now %}
<div class='forecast-table'>
    <div class='container'>
        <div class='forecast-container weather'>
            <!-- 当日天气 -->
            <div class='today forecast'>
                <!-- 顶部 时间-->
                <div class='forecast-header weather-date'>更新时间：{{ iweather.update_loc}}</div>
                <!-- 内容 -->
                <div class='forecast-content'>
                    <div class='location weather-city'>{{ iweather.city }}</div>
                    <div class='degree'>
                        <div class='num weather-tmp'>{{ iweather.tmp }}</div>
                        <div class='forecast-icon'>
                            <!--<img class='weather-cond' src="#" alt='' width=90>-->
                            {{ iweather.cond_txt }}
                        </div>
                        <!--<div class='forecast-icon'>-->
                            <!--<img class='weather-cond' src="#" alt='' width=90>-->
                        <!--</div>-->
                        <div class='forecast-icon'>
                            <!--<img class='weather-cond' src="#" alt='' width=90>-->
                            {{ iweather.aqi_qlty }}
                        </div>
                    </div>
                    <span class='weather-wind'><img src="{% static 'bootstrap/img/weather_icons/icon-wind.png' %}" alt=''>{{ iweather.wind_sc }}</span>
                    <span class='weather-cond-txt'>{{ iweather.cond_txt }}</span>
                </div>
            </div>
            <!-- 天气预报 -->
            {% for iforecast in iweather.weatherforecast_set.all %}
            <div class='forecast'>
                <div class='forecast-header'>
                    <div class='day weather-forecast-date'>{{ iforecast.fc_date }}</div>
                </div>
                <div class='forecast-content weather-img'>
                    <div class='forecast-icon'>
                        <!--- <img class='weather-forecast-cond' src="#" alt='' width=48> --->
                        {{ iforecast.fc_txt_d }} 转 {{ iforecast.fc_txt_n }}
                    </div>
                    <div class='degree weather-forecast-tmp-max'>{{ iforecast.fc_tmp_max }}</div>
                    <small class='weather-forecast-tmp-min'>{{ iforecast.fc_tmp_min }}</small>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<br><br><br><br><br><br><br><br>
{% endfor %}
</div>

<hr>
<link href="{% static 'bootstrap/css/weather.css' %}" rel="stylesheet" type="text/css">
<style>
    .weather-img {
        padding: 50px 0px 20px !important;
    }
</style>
{% endblock %}

tools/templates/tools/tools_weather_get_data.html
{{ status }}

tools/templates/tools/tools_weather_statistics.html
{% extends 'base.html' %}

{% block title %}历史天气数据统计{% endblock %}

{% block content %}
{% load static %}
<div class='container'>
    {% for city in data %}
    <div class='row'>
        <div class='panel panel-success'>
            <div class='panel-heading'><h3>{{ city }}</h3></div>
            <div class='panel-body'>
                <div class='col-md-6'>
                    <p class='text-center text-warning'>历史气温趋势图</p>
                    <canvas class='tmp'></canvas>
                </div>
                <div class='col-md-6'>
                    <p class='text-center text-warning'>空气质量分布图</p>
                    <canvas class='aqi'></canvas>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<script src="{% static 'bootstrap/js/Chart.js' %}"></script>
<script>
    var ctxTmp = []
    var tmpData = []
    var tmpChart = []

    var ctxAqi = []
    var aqiData = []
    var aqiChart = []

    var aqiColor = ['#99CCFF', '#CCFFFF', '#FFCC33', '#CC9933', '#663333', '#99CCCC', '#FFCCCC']
{% for city,info in data.items %}
    var i = {{forloop.counter0}}

    //每日温度图（最高和最低气温)
    ctxTmp[i] = $(".tmp").get(i).getContext("2d");

    var labelsDate = []
    var tmpMin = []
    var tmpMax = []
    {% for date, value in info.tmp_min.items %}
        labelsDate.push('{{ date }}')
        tmpMin.push({{ value.tmp__min }})
    {% endfor %}

    {% for date, value in info.tmp_max.items %}
        tmpMax.push({{ value.tmp__max }})
    {% endfor %}

    tmpData[i] = {
        labels : labelsDate,
        datasets : [
                    {
                                fillColor : "rgba(220,220,220,0.5)",
                                strokeColor : "rgba(220,220,220,1)",
                                pointColor : "rgba(220,220,220,1)",
                                pointStrokeColor : "#fff",
                                data : tmpMin
                            },
                    {
                                fillColor : "rgba(151,187,205,0.5)",
                                strokeColor : "rgba(151,187,205,1)",
                                pointColor : "rgba(151,187,205,1)",
                                pointStrokeColor : "#fff",
                                data : tmpMax
                            }
                    ]
    }

    tmpChart[i] = new Chart(ctxTmp[i]).Line(tmpData[i], {responsive: true});

    //空气质量统计饼形图
    ctxAqi[i] = $(".aqi").get(i).getContext("2d");

    aqiData[i] = [
        {% for key, value in info.aqi_counter.items %}
        {
            value: {{ value }},
            color: aqiColor[{{ forloop.counter0 }}],
            label: '{{ key }}'
        },
        {% endfor %}
    ]

    aqiChart[i] = new Chart(ctxAqi[i]).Pie(aqiData[i], {responsive: true});
{% endfor %}
</script>
{% endblock %}