blog/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.BlogPaginatorView.as_view(), name='index'),
    url(r'^page/(?P<page>[0-9]+)$', views.BlogPaginatorView.as_view(), name='paginator'),
    url(r'^tags/(?P<tag_id>[0-9]+)/page/(?P<page>[0-9]+)$', views.BlogPaginatorView.as_view(), name='tags'),
    url(r'^(?P<pk>[0-9]+)$', views.BlogDetailView.as_view(), name='detail'),
    url(r'^comment/(?P<pk>[0-9]+)/$', views.BlogCommentRedirectView.as_view(), name='blog_redirect'),
    url(r'^search/$', views.BlogSearchView.as_view(), name='blog_search')
]

jaydenfoo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from blog import views as blog_views
from .views import RegisterView


urlpatterns = [
    url(r'^$', blog_views.BlogPaginatorView.as_view()),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tools/', include('tools.urls', namespace='tools')),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
    url(r'^album/', include('album.urls', namespace='album')),
    url(r'^register/$', RegisterView, name='register'),
    url(r'^wechat/', include('wechat.urls', namespace='wechat')),
    url(r'^markdownx/', include('markdownx.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify


class Tag(models.Model):
    '''文章标签'''
    name = models.CharField(max_length=10, unique=True) # 标签名称
    count_post = models.IntegerField(default=0, editable=False) # 包含该标签的文章

    def __str__(self):
        return self.name

class Article(models.Model):
    '''文章'''
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=10)
    pub_date = models.DateTimeField('date publishded')
    abstract = models.CharField(max_length=2000, blank=True)
    # content = UEditorField(u'content    ', width=600, height=300, toolbars="full", imagePath="blog/article_image/", filePath="blog/article_file/", upload_settings={"imageMaxSize":1204000}, settings={}, command=None, blank=True)
    content = MarkdownxField()
    count_hit = models.IntegerField(default=0, editable=False)
    tags = models.ManyToManyField(Tag, blank=True)

    @property
    def formatted_markdown(self):
        return markdownify(self.content)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('blog.views.BlogDetailView', args=[str(self.id)])

class Comment(models.Model):
    '''对文章的评论'''
    nick_name = models.CharField(max_length=10)
    content = models.CharField(max_length=2000)
    pub_date = models.DateTimeField(auto_now=True)
    article  = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return self.nick_name + ': ' + self.content[:10]

blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['nick_name', 'content']

blog/views.py
from django.shortcuts import get_object_or_404
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from hitcount.views import HitCountDetailView

from .models import Tag, Article
from .forms import CommentForm
from .search import search


class BlogPaginatorView(generic.ListView):
    """
    文章列表分页视图
    """

    template_name = 'blog/blog_paginator.html'
    context_object_name = 'article_paginator_list'

    def get_queryset(self):
        # 使用标签分类文章
        if 'tag_id' in self.kwargs:
            self.tag = get_object_or_404(Tag, id=self.kwargs['tag_id'])
            article_list = self.tag.article_set.order_by('-pub_date')
        else:
            article_list = Article.objects.order_by('-pub_date')

        # 每页显示10篇文章
        paginator = Paginator(article_list, 10)
        page = self.kwargs.get('page', 1)

        try:
            article_paginated = paginator.page(page)
        except PageNotAnInteger:
            article_paginated = paginator.page(1)
        except EmptyPage:
            article_paginated = paginator.page(paginator.num_pages)
        return article_paginated

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag_list'] = Tag.objects.all()
        if 'tag_id' in self.kwargs:
            context['this_tag'] = self.tag
        return context


class BlogDetailView(HitCountDetailView):
    """
    文章详细展示页视图
    """

    model = Article
    template_name = 'blog/blog_detail.html'
    context_object_name = 'this_article'
    count_hit = True  # 打开统计点击数功能

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        context['tag_list'] = Tag.objects.all()
        self.article = get_object_or_404(Article, id=self.kwargs['pk'])
        context['comment_list'] = self.article.comment_set.all()
        return context


class BlogCommentRedirectView(generic.base.RedirectView):
    """
    文章评论重定向试图．
    提交评论时，将评论和当前文章关联，保存评论，
    使用重定向刷新文章页面．
    """

    # TODO: 使用Ajax实现该功能

    permanent = False
    pattern_name = 'blog:detail'  # 重定向的目标地址

    def get_redirect_url(self, *args, **kwargs):
        if self.request.method == 'POST':
            this_article = get_object_or_404(Article, pk=kwargs['pk'])
            form = CommentForm(self.request.POST)
            if form.is_valid():
                form_clean = CommentForm(form.cleaned_data)
                new_comment = form_clean.save(commit = False)
                new_comment.article = this_article
                new_comment.save()
        return super().get_redirect_url(*args, **kwargs)


class BlogSearchView(generic.ListView):

    template_name = 'blog/blog_search.html'
    context_object_name = 'article_search_results'

    def get_queryset(self):
        pattern = self.request.GET.get('pattern')
        queryset = list()
        if pattern:
            res = search(pattern)
            for index, hit in enumerate(res):
                item = dict()
                item['id'] = getattr(hit, 'id')
                item['pub_date'] = getattr(hit, 'pub_date')
                if hasattr(hit.meta.highlight, 'title'):
                    item['title'] = getattr(hit.meta.highlight, 'title')[0]
                else:
                    item['title'] = hit.title
                if hasattr(hit.meta.highlight, 'content'):
                    item['content'] = getattr(hit.meta.highlight, 'content')[0]
                else:
                    item['content'] = hit.content
                queryset.append(item)
        return queryset

blog/templates/blog/blog_detail.html
{% extends "base.html" %}

{% block title %} {{ this_article.title }} {% endblock %}


{% block content %}

<div class="container-fluid">
  <div class="row">
    <!-- 文章主体 -->
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">
          <h2 class="text-center">{{ this_article.title }}</h2>
          <br>
          <p class="text-center no-margin-bottom"><span class="text-success">Author:</span> {{ this_article.author }} &nbsp&nbsp&nbsp<span class="text-success">Date:</span> {{ this_article.pub_date|date:"Y-m-d"}} &nbsp&nbsp&nbsp<span class="text-success">Read:</span> {{hitcount.total_hits}}
          <hr class="no-margin-top">
          <p>{{ this_article.formatted_markdown|safe }}</p>
        </div>
      </div>
    </div>
    <!-- 标签栏 -->
    <div class="col-md-4">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">全部标签</h3>
        </div>
        <div class="panel-body">
        {% for tag in tag_list %}
        <a href="{% url 'blog:tags' tag.id 1 %}"><u>{{ tag.name }}</u></a>&nbsp
        {% empty %}
        <li> No tags</li>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>

<!-- 评论显示-->
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">评论：</div>
        <div class="panel-body">
        {% for comment in comment_list %}
          <p class="text-info">{{comment.nick_name}}: </p>
          <p>{{comment.content}}</p>
          <small class="text-primary">{{ comment.pub_date|date:'Y-m-d' }}</small>
          <hr>
        {% empty %}
          <p>没有评论</p>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>


<!-- 评论表单 -->
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading">发表评论：</div>
        <div class="panel-body">
        	<form action="{% url 'blog:blog_redirect' this_article.id %}" method="post" class="col-lg-6 col-md-6 col-sm-6 col-xs-10">
        	  {% csrf_token %}
        	  <fieldset>
        	    <div class="form-group">
        	      {{ form.nick_name.errors }}
        	     	<label class="control-label" for="{{ form.nick_name.id_for_label }}">昵称</label>
        	      <input type="text" class="form-control" id="{{ form.nick_name.id_for_label }}" name="{{ form.nick_name.html_name }}" placeholder="请输入您的大名"/>
        	    </div>
        	    <div class="form-group">
        	      {{ form.content.errors }}
        	      <label class="control-label" for="{{ form.content.id_for_label }}">评论</label>
        	      <div>
        	        <textarea rows="3" class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.html_name }}" placeholder="开始评论"></textarea>
        	      </div>
        	    </div>
        	    <div class="form-group">
      					<div>
        					<button type="submit" class="btn btn-primary">提交</button>
      					</div>
    					</div>
        	  </fieldset>
			</form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- style -->
<style type="text/css">
img {
  max-width: 100%;
  height: auto;
  display: block;
}
.no-margin-top {
    margin-top: 0; 
}
.no-margin-bottom {
    margin-bottom: 0;
}

</style>

<!-- script -->
<script type="text/javascript" >
//文章中的代码高亮
  SyntaxHighlighter.all();

//最笨的方法控制导航栏
$(function () {
      $('#nav_blog').parent().addClass('active')
      $('#nav_album').parent().removeClass('active')
      $('#nav_zheteng').parent().removeClass('active')
    })
</script>

{% endblock %}

blog/templates/blog/blog_paginator.html
{% extends "base.html" %}
{% block title %}博客{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <!-- 文章列表 -->
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">
        <!-- 如果是标签列表  -->
        {% if this_tag %}
          <h3 class="text-info">{{ this_tag.name }}</h3>
          <br>
        {% endif %}

        {% for article in article_paginator_list %}
          <h4><a href="{% url 'blog:detail' article.id %}"> {{ article.title }}</a><small>&nbsp&nbsp&nbsp&nbsp{{ article.pub_date|date:"Y-m-d"}}</small></h4>
          <p>{{ article.abstract }}</p>
          <hr>
        {% empty %}
          <h4>还没有文章</h4>
        {% endfor %}
        </div>
      </div>
    </div>

    <!-- 标签栏 -->
    <div class="col-md-4">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">全部标签</h3>
        </div>
        <div class="panel-body">
        {% for tag in tag_list %}
        <a href="{% url 'blog:tags' tag.id 1 %}"><u>{{ tag.name }}</u></a>&nbsp
        {% empty %}
        <li> No tags</li>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>

  <!-- 分页 -->
  <!-- TODO: 条件情况判断 -->
  <div class="row">
  	<div class="col-md-4 col-md-offset-2">
  		<ul class="pager">
  		{% if article_paginator_list.has_previous %}
  		  {% if this_tag %}
  		    <li><a href="{% url 'blog:tags' this_tag.id article_paginator_list.previous_page_number %}">上一页</a></li>
  		  {% else %}
  		    <li><a href="{% url 'blog:paginator' article_paginator_list.previous_page_number %}">上一页</a></li>
  		  {% endif %}

  		{% else %}
  		  <li class="disabled"><a>上一页</a></li>
  		{% endif %}

  		{{ article_paginator_list.number }} of {{ article_paginator_list.paginator.num_pages }}

      {% if article_paginator_list.has_next %}
        {% if this_tag %}
          <li><a href="{% url 'blog:tags' this_tag.id article_paginator_list.next_page_number %}">下一页</a></li>
        {% else %}
          <li><a href="{% url 'blog:paginator' article_paginator_list.next_page_number %}">下一页</a></li>
        {% endif %}
      {% else %}
        <li class="disabled"><a>下一页</a></li>
      {% endif %}
      </ul>
  	</div>
  </div>
</div>

<script type="text/javascript">
//最笨的方法控制导航栏
$(function () {
      $('#nav_blog').parent().addClass('active')
      $('#nav_album').parent().removeClass('active')
      $('#nav_zheteng').parent().removeClass('active')
    })
</script>

{% endblock %}

blog/templates/blog/blog_search.html
{% extends "base.html" %}
{% block title %}博客搜索结果{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <!-- 文章列表 -->
    <div class="col-md-8">
      <div class="panel panel-default">
        <div class="panel-body">
        {% for article in article_search_results %}
          <h4><a href="{% url 'blog:detail' article.id %}"> {{ article.title | safe}}</a><small>&nbsp&nbsp&nbsp&nbsp{{ article.pub_date|date:"Y-m-d"}}</small></h4>
          <p>{{ article.content | safe }}</p>
          <hr>
        {% empty %}
          <h4>没有搜索结果</h4>
        {% endfor %}
        </div>
      </div>
    </div>

  </div>

  <!-- 分页 -->
  <!-- TODO: 条件情况判断 -->
  <div class="row">
  	<div class="col-md-4 col-md-offset-2">
  		<ul class="pager">
  		{% if article_paginator_list.has_previous %}
  		  {% if this_tag %}
  		    <li><a href="{% url 'blog:tags' this_tag.id article_paginator_list.previous_page_number %}">上一页</a></li>
  		  {% else %}
  		    <li><a href="{% url 'blog:paginator' article_paginator_list.previous_page_number %}">上一页</a></li>
  		  {% endif %}

  		{% else %}
  		  <li class="disabled"><a>上一页</a></li>
  		{% endif %}

  		{{ article_paginator_list.number }} of {{ article_paginator_list.paginator.num_pages }}

      {% if article_paginator_list.has_next %}
        {% if this_tag %}
          <li><a href="{% url 'blog:tags' this_tag.id article_paginator_list.next_page_number %}">下一页</a></li>
        {% else %}
          <li><a href="{% url 'blog:paginator' article_paginator_list.next_page_number %}">下一页</a></li>
        {% endif %}
      {% else %}
        <li class="disabled"><a>下一页</a></li>
      {% endif %}
      </ul>
  	</div>
  </div>
</div>

<script type="text/javascript">
//最笨的方法控制导航栏
$(function () {
      $('#nav_blog').parent().addClass('active')
      $('#nav_album').parent().removeClass('active')
      $('#nav_zheteng').parent().removeClass('active')
    })
</script>

{% endblock %}