album/urls.py
#!/usr/bin/env python
# encoding: utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
       url(r'^$', views.AlbumIndexView.as_view(), name='index'),
       url(r'^(?P<pk>\d+)$', views.AlbumDetailView.as_view(), name='detail'),
]

blog/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.BlogPaginatorView.as_view(), name='index'),
    url(r'^page/(?P<page>[0-9]+)$', views.BlogPaginatorView.as_view(), name='paginator'),
    url(r'^tags/(?P<tag_id>[0-9]+)/page/(?P<page>[0-9]+)$', views.BlogPaginatorView.as_view(), name='tags'),
    url(r'^(?P<pk>[0-9]+)$', views.BlogDetailView.as_view(), name='detail'),
    url(r'^comment/(?P<pk>[0-9]+)/$', views.BlogCommentRedirectView.as_view(), name='blog_redirect'),
    url(r'^search/$', views.BlogSearchView.as_view(), name='blog_search')
]

jaydenfoo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from blog import views as blog_views
from .views import RegisterView


urlpatterns = [
    url(r'^$', blog_views.BlogPaginatorView.as_view()),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tools/', include('tools.urls', namespace='tools')),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
    url(r'^album/', include('album.urls', namespace='album')),
    url(r'^register/$', RegisterView, name='register'),
    url(r'^wechat/', include('wechat.urls', namespace='wechat')),
    url(r'^markdownx/', include('markdownx.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

album/models.py
#-*- coding: utf-8 -*-
from django.db import models


# 自定义动态路径名，如果upload_to参数是可调用的，则调用的函数会覆盖默认的generate_filename函数
def generate_filename(self, filename):
    url = 'album/%s/%s' %(self.album.e_name, filename)
    return url

class Album(models.Model):
    '''相册数据模型'''
    name = models.CharField(max_length=20, unique=True)
    e_name = models.CharField(max_length=20, unique=True)
    desc = models.TextField(blank=True)
    established_date = models.DateTimeField(auto_now_add=True, verbose_name='Establish Date')
    count_hit = models.IntegerField(default=0, editable=False) # 未使用

    def __str__(self):
        return self.name

class Photo(models.Model):
    '''照片数据模型'''
    name = models.CharField(max_length=20, blank=True)
    desc = models.TextField(blank=True)
    album = models.ForeignKey(Album) # 所属相册
    image = models.ImageField(upload_to=generate_filename)
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Publish Date')
    as_cover = models.BooleanField(default=False) # 是否作为相册封面

album/views.py
# -*- coding:utf-8 -*-
from django.views import generic
from django.shortcuts import get_object_or_404

from .models import Album
from hitcount.views import HitCountDetailView


class AlbumIndexView(generic.ListView):
    '''相册首页视图'''
    template_name = 'album/album_index.html'
    context_object_name = 'album_list'

    def get_queryset(self):
        return Album.objects.order_by('-established_date')

class AlbumDetailView(HitCountDetailView):
    '''相册内图片展示视图'''
    model = Album
    template_name = 'album/album_detail.html'
    context_object_name = 'this_album'
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['this_album'] = get_object_or_404(Album, id=self.kwargs['pk'])
        return context

blog/views.py
from django.shortcuts import get_object_or_404
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from hitcount.views import HitCountDetailView

from .models import Tag, Article
from .forms import CommentForm
from .search import search


class BlogPaginatorView(generic.ListView):
    """
    文章列表分页视图
    """

    template_name = 'blog/blog_paginator.html'
    context_object_name = 'article_paginator_list'

    def get_queryset(self):
        # 使用标签分类文章
        if 'tag_id' in self.kwargs:
            self.tag = get_object_or_404(Tag, id=self.kwargs['tag_id'])
            article_list = self.tag.article_set.order_by('-pub_date')
        else:
            article_list = Article.objects.order_by('-pub_date')

        # 每页显示10篇文章
        paginator = Paginator(article_list, 10)
        page = self.kwargs.get('page', 1)

        try:
            article_paginated = paginator.page(page)
        except PageNotAnInteger:
            article_paginated = paginator.page(1)
        except EmptyPage:
            article_paginated = paginator.page(paginator.num_pages)
        return article_paginated

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag_list'] = Tag.objects.all()
        if 'tag_id' in self.kwargs:
            context['this_tag'] = self.tag
        return context


class BlogDetailView(HitCountDetailView):
    """
    文章详细展示页视图
    """

    model = Article
    template_name = 'blog/blog_detail.html'
    context_object_name = 'this_article'
    count_hit = True  # 打开统计点击数功能

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        context['tag_list'] = Tag.objects.all()
        self.article = get_object_or_404(Article, id=self.kwargs['pk'])
        context['comment_list'] = self.article.comment_set.all()
        return context


class BlogCommentRedirectView(generic.base.RedirectView):
    """
    文章评论重定向试图．
    提交评论时，将评论和当前文章关联，保存评论，
    使用重定向刷新文章页面．
    """

    # TODO: 使用Ajax实现该功能

    permanent = False
    pattern_name = 'blog:detail'  # 重定向的目标地址

    def get_redirect_url(self, *args, **kwargs):
        if self.request.method == 'POST':
            this_article = get_object_or_404(Article, pk=kwargs['pk'])
            form = CommentForm(self.request.POST)
            if form.is_valid():
                form_clean = CommentForm(form.cleaned_data)
                new_comment = form_clean.save(commit = False)
                new_comment.article = this_article
                new_comment.save()
        return super().get_redirect_url(*args, **kwargs)


class BlogSearchView(generic.ListView):

    template_name = 'blog/blog_search.html'
    context_object_name = 'article_search_results'

    def get_queryset(self):
        pattern = self.request.GET.get('pattern')
        queryset = list()
        if pattern:
            res = search(pattern)
            for index, hit in enumerate(res):
                item = dict()
                item['id'] = getattr(hit, 'id')
                item['pub_date'] = getattr(hit, 'pub_date')
                if hasattr(hit.meta.highlight, 'title'):
                    item['title'] = getattr(hit.meta.highlight, 'title')[0]
                else:
                    item['title'] = hit.title
                if hasattr(hit.meta.highlight, 'content'):
                    item['content'] = getattr(hit.meta.highlight, 'content')[0]
                else:
                    item['content'] = hit.content
                queryset.append(item)
        return queryset

album/templates/album/album_detail.html
{% extends 'base.html' %}

{% block title %}{{ this_album.name }}{% endblock %}

{% block content %}
{% load thumbnail %}
<!-- 相册标题行 -->
<div class="container">
    <div class="row">
        <h2 class="text-center">{{ this_album.name }}</h2>
        <p class="text-center no-margin-bottom"><span class="text-success">发布日期:</span> {{ this_album.established_date }} &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span class="text-success">点击数:</span> {{hitcount.total_hits}}
        <hr>
        <br>
    </div>
</div>

<!-- 瀑布式图片显示区 -->
<div class="container">
		<div class="grid">
		    {% for photo in this_album.photo_set.all %}
		        <div class="grid-item">
		            <a href="{{ photo.image.url }}" class='portfolio-box' data-gallery>
		                <image src="{% thumbnail photo.image 400x400 %}" class="img-responsive" alt="图片被浏览器吃了（T﹏T）">
		            </a>
		        </div>
		    {% endfor %}
		</div>
</div>

<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-use-bootstrap-modal="false">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>

<script type="text/javascript" >
    $(document).ready(function () {
        var $grid = $('.grid').masonry({
                                itemSelector: '.grid-item',
                                    columnWidth: '.grid-item',
                                    gutter: 10,
                                    percentPosition: true
                                });

    $grid.imagesLoaded().progress( function() {
    //init Masonry after all images have loaded
        $grid.masonry('layout')
    });


//最笨的方法控制导航栏
      $('#nav_blog').parent().removeClass('active')
      $('#nav_album').parent().addClass('active')
      $('#nav_zheteng').parent().removeClass('active')
    })
</script>

<style type="text/css">
    .grid-item {
        float:left;
        width:100%;
        margin-bottom:10px
    }
    @media screen and (min-width: 768px) {
        .grid-item { width: 32%;  }
    }

</style>
{% endblock %}

album/templates/album/album_index.html
{% extends 'base.html' %}

{% block title %}Album{% endblock %}

{% block content %}
{% load thumbnail %}
<div class='container'>
    <br><br><br>
    <div class='grid'>
        {% for album in album_list %}
        <div class="grid-item">
            <div class="thumbnail">
                <a title="huace" href="{% url 'album:detail' album.id %}" class='thumbnail' >
                {% for photo in album.photo_set.all %}
                    {% if photo.as_cover %}
                        <image src="{% thumbnail photo.image 400x400 %}" class="img-responsive" alt="图片被浏览器吃了（T﹏T）">
                    {% endif %}
                {% endfor %}
                </a>
                <div class="caption">
                    <h3 class="text-info">{{ album.name }}</h3>
                    <p>{{ album.desc }}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <p>还没有添加相册</p>
        {% endfor %}
    </div>
</div>

<script type="text/javascript" >
//masonry排列
$(document).ready(function () {
    var $grid = $('.grid').masonry({
                            itemSelector: '.grid-item',
                                columnWidth: '.grid-item',
                                gutter: 10,
                                percentPosition: true
                            });

		$grid.imagesLoaded().progress( function() {
		//init Masonry after all images have loaded
		    $grid.masonry('layout')
		});
})

//最笨的方法控制导航栏
$(function () {
      $('#nav_blog').parent().removeClass('active')
      $('#nav_album').parent().addClass('active')
      $('#nav_zheteng').parent().removeClass('active')
    })
</script>

<style type="text/css">
    .grid-item {
        float:left;
        width:100%;
        margin-bottom:10px
    }
    @media screen and (min-width: 768px) {
        .grid-item { width: 32%;  }
    }
</style>

{% endblock %}