blog/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.BlogPaginatorView.as_view(), name='index'),
    url(r'^page/(?P<page>[0-9]+)$', views.BlogPaginatorView.as_view(), name='paginator'),
    url(r'^tags/(?P<tag_id>[0-9]+)/page/(?P<page>[0-9]+)$', views.BlogPaginatorView.as_view(), name='tags'),
    url(r'^(?P<pk>[0-9]+)$', views.BlogDetailView.as_view(), name='detail'),
    url(r'^comment/(?P<pk>[0-9]+)/$', views.BlogCommentRedirectView.as_view(), name='blog_redirect'),
    url(r'^search/$', views.BlogSearchView.as_view(), name='blog_search')
]

jaydenfoo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from blog import views as blog_views
from .views import RegisterView


urlpatterns = [
    url(r'^$', blog_views.BlogPaginatorView.as_view()),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tools/', include('tools.urls', namespace='tools')),
    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),
    url(r'^album/', include('album.urls', namespace='album')),
    url(r'^register/$', RegisterView, name='register'),
    url(r'^wechat/', include('wechat.urls', namespace='wechat')),
    url(r'^markdownx/', include('markdownx.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="baidu-site-verification" content="Z4LwjUIXWN" />
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %} {% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- codehilite style for code highlight -->
    <link href="{% static 'codehilite_styles.css' %}" rel="stylesheet">

    <!-- jquery -->
    <script type="text/javascript" src="{% static 'bootstrap/js/jquery.min.js' %}"></script>

    <!-- Bootstrap-js -->
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- font-awesome -->
    <link rel="stylesheet" href="{% static 'bootstrap/font-awesome/css/font-awesome.min.css' %}" type="text/css">

    <!-- 来之于首页样式 for album-->
    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/animate.min.css' %}" type="text/css">

    <!-- Custom CSS 为了不影响其他页面，将只在相册中用到的效果从creative.css中提取出来放到album.css -->
    <!--link rel="stylesheet" href="{% static 'bootstrap/css/creative.css' %}" type="text/css"-->
    <link rel="stylesheet" href="{% static 'bootstrap/css/album.css' %}" type="text/css">

    <!-- Plugin JavaScript -->
    <script src="{% static 'bootstrap/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/jquery.fittext.js' %}"></script>
    <script src="{% static 'bootstrap/js/wow.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'bootstrap/js/creative.js' %}"></script>

    <!-- 幻灯片效果 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/blueimp-gallery.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-image-gallery.min.css' %}">

    <script src="{% static 'bootstrap/js/jquery.blueimp-gallery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap-image-gallery.min.js' %}"></script>

    <!-- 图片布局 -->

    <script src="{% static 'bootstrap/js/masonry.pkgd.min.js' %}"></script>
    <!-- 检测图片是否加载完成 -->
    <script src="{% static 'bootstrap/js/imagesloaded.pkgd.min.js' %}"></script>
  </head>
  <body>
    <!-- 导航栏 -->
   <nav class="navbar navbar-default">
	 <div class="container-fluid">
	    <div class="navbar-header">
		    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">JAYDEN FOO</a>
	    </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><a id='nav_blog' href="{% url 'blog:paginator' 1 %}">博客<span class="sr-only">(current)</span></a></li>
	        <li><a id='nav_album' href="{% url 'album:index' %}">画册</a></li>
	        <li><a id='nav_zheteng' href="{% url 'tools:index' %}">折腾</a></li>
	      </ul>
          <ul class='nav navbar-nav navbar-right'>
              <li><form class="form-inline" action="{% url 'blog:blog_search' %}" method="get">
                  <input class="form-control" type="search" placeholder="Search" name="pattern">
                  <button class="btn" type="submit">搜索</button>
              </form></li>
              {% if user.is_authenticated %}
                <li><p class='navbar-text'><strong>{{ user.username }}</strong></p></li>
                <li><a href="{% url 'logout' %}?next={{ request.path }}">注销</a></li>
              {% else %}
                <li><a href="{% url 'login' %}?next={{ request.path }}">登录</a><li>
                <li><a href="{% url 'register' %}">注册</a><li>
              {% endif %}
          </ul>
	    </div>
	  </div>
	</nav>
    {% block content %} {% endblock %}
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta name="google-site-verification" content="xe97-E4AFG45CueS1By--C6pjdscg7kpDvsYkAsFOHQ" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="vm_ubuntu" >

    <title>Jayden Foo</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'bootstrap/font-awesome/css/font-awesome.min.css' %}" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/animate.min.css' %}" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/creative.css' %}" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Jayden Foo</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">自述</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#module">模块</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#album">图墙</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">勾搭</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>就是爱折腾</h1>
                <hr>
                <p>生命不息，折腾不止</p>
                <p>生命不息，折腾不止</p>
                <p>生命不息，折腾不止</p>
                <a class="page-scroll" href="#about"><i class="fa fa-4x fa-angle-double-down"></i></a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">逗B</h2>
                    <hr class="light">
                    <p class="text-faded">永远不要跟一个纯傻逼争论，因为他会把你的智商拉到和他一个水平，然后用他多年当傻逼的丰富经验打败你。。。。。。</p>
                    <a href="#module" class="btn btn-default btn-xl page-scroll">芝麻开门！</a>
                </div>
            </div>
        </div>
    </section>

    <section id="module">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">开发中</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="{% url 'blog:index'%}"><i class="fa fa-4x fa-book wow bounceIn text-primary"></i>
                        <h3>博客</h3></a>
                        <p class="text-muted"></p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="{% url 'album:index' %}"><i class="fa fa-4x fa-file-photo-o wow bounceIn text-primary" data-wow-delay=".1s"></i>
                            <h3>画册</h3></a>
                        <p class="text-muted"></p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="{% url 'tools:index' %}"<i class="fa fa-4x fa-keyboard-o wow bounceIn text-primary" data-wow-delay=".1s"></i>
                            <h3>瞎折腾</h3></a>
                        <p class="text-muted"></p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <a href="#about"><i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".1s"></i>
                            <h3>关于我</h3></a>
                        <p class="text-muted"></p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="no-padding" id="album">
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static 'bootstrap/img/portfolio/1.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static 'bootstrap/img/portfolio/2.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static 'bootstrap/img/portfolio/3.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static 'bootstrap/img/portfolio/4.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static 'bootstrap/img/portfolio/5.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="{% static 'bootstrap/img/portfolio/6.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>想要看更多</h2>
                <a href="{% url 'album:index' %}" class="btn btn-default btn-xl wow tada">点我</a>
            </div>
        </div>
    </aside>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">勾搭</h2>
                    <hr class="primary">
                    <p>Send me email!</p>
                </div>
                <div class="col-lg-8 col-lg-offset-2 text-center ">
                    <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p>icebrick@163.com</p>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'bootstrap/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/jquery.fittext.js' %}"></script>
    <script src="{% static 'bootstrap/js/wow.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'bootstrap/js/creative.js' %}"></script>

</body>

</html>

templates/register.html
{% extends 'base.html' %}

{% block title %}注册{% endblock %}

{% block content %}
<div class='container'>
    <div class='row'>
        <div class='col-md-offset-3 col-md-6'>
            <div class='center-block'>
                {% if form.non_field_errors %}
                    <div class='alert alert-warning' role='alert'>{{ form.non_field_errors }}</div>
                {% endif %}
                <div class='panel panel-default'>
                    <div class='panel-heading'>
                        <strong>注册</strong>
                    </div>
                    <div class='panel-body'>
                        <form action="{% url 'register' %}" method='post'>
                            {% csrf_token %}
                            {% for field in form %}
                                <div class='form-group'>
                                    {{ field.label_tag }}
                                    {% if field.errors %}
                                    <span class='text-danger pull-right'>{{ field.errors }}</span>
                                    {% endif %}
                                    {{ field }}
                                    <p class='text-muted'>{{ field.help_text }}</p>
                                </div>
                            {% endfor %}
                            <button type='submit' class='btn btn-defautl'>注册</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .center-block {
        display: block;
        margin-left: auto;
        margin-right: auto;
        }

    .element {
        .center-block();
            }
</style>
{% endblock %}